services:
  web:
    build:
      context: .
      args:
        API_BASE_URL: ${API_BASE_URL:-http://127.0.0.1:8000}
    image: moodleng:latest
    ports:
      - "${HOST_PORT:-8080}:80"
    restart: unless-stopped
    env_file:
      - .env
